[ION-938] Allow pointing our package.json to the slate-plugins fork
FirstResonance/slate-plugins pull request #4
Opened 2020-09-01 09:08 UTC by gitstart-firstresonance

## Issue

## What I did

## Checklist

- [x] The new code matches the existing patterns and styles.
- [x] The stories still work (run `yarn storybook`).
- [x] The stories are updated when relevant: `stories` for plugins, `knobs` for options.

2020-09-01 18:33 UTC, alantrrs commented
@gitstart-firstresonance The objective here is just to allow us to point to this repo as a dependency from our package.json for when we're testing new things that haven't landed in the main repository. Let's not make any changes that are not required to make that happen. We want to continue to contribute to the main repository, not make this our own, so the fewer the changes, the better.

2020-09-01 19:14 UTC, gitstart-firstresonance commented
> @gitstart-firstresonance The objective here is just to allow us to point to this repo as a dependency from our package.json for when we're testing new things that haven't landed in the main repository. Let's not make any changes that are not required to make that happen. We want to continue to contribute to the main repository, not make this our own, so the fewer the changes, the better.

Yes. The changes made were required to install this as a dependency as we would be building on installation. Other changes are github action workflow. This changes does not affect making contributing the changes back to the main repo

2020-09-02 16:26 UTC, alantrrs requested changes
- [x] Please provide an estimate for this. I don't see it here nor in the gitstart dashboard.
- [x] The default branch is `next`. Please branch out of there and make a PR against that branch
- [ ] Please only keep the specific changes that allow us to use it as dependency. I know other changes don't affect the build or contributing back, but I want this PR to be minimal.

2020-09-03 07:09 UTC, gitstart-firstresonance commented
Unnecessary changes have been removed. Any other change is needed to enable seamless installation and development

2020-09-04 17:11 UTC, alantrrs submitted a review, later dismissed
How are you testing that installing the repo works? After requiring it from tchami:
``` 
"@udecode/slate-plugins": "github:FirstResonance/slate-plugins#dab27a4e16f36c6030410cde98a85973db0abeb8",
```
I'm getting the following error:

![image](https://user-images.githubusercontent.com/689720/92268071-97f2d380-ee96-11ea-83cf-e8d08cde71e8.png)

2020-09-04 17:52 UTC, gitstart-firstresonance commented
> How are you testing that installing the repo works? After requiring it from tchami:
> 
> ```
> "@udecode/slate-plugins": "github:FirstResonance/slate-plugins#dab27a4e16f36c6030410cde98a85973db0abeb8",
> ```
> 
> I'm getting the following error:
> 
> ![image](https://user-images.githubusercontent.com/689720/92268071-97f2d380-ee96-11ea-83cf-e8d08cde71e8.png)

Dint't experince that which may be because the tchami branch used does not have the latest changes which uses `getSelectableElement` as it does not seem to be available in the slate-plugins next branch

2020-09-04 18:35 UTC, alantrrs commented
@gitstart-firstresonance I see, seems like our `next` branch was outdated, I just pulled the latest from upstream. Please rebase the `next` branch.

2020-09-05 06:09 UTC, gitstart-firstresonance commented
> @gitstart-firstresonance I see, seems like our `next` branch was outdated, I just pulled the latest from upstream. Please rebase the `next` branch.

ohh. Done

2020-09-08 16:31 UTC, alantrrs requested changes
I'm still getting errors using it in tchami, now it seems there might be a react versions mismatch. I wonder if it's related to using 2 different package managers.
Can you look into it? Please verify by requiring it in tachmi.

![image](https://user-images.githubusercontent.com/689720/92503276-ddc0dc00-f1b5-11ea-96fc-beb34f60d570.png)

2020-09-08 16:31 UTC, alantrrs commented on package.json
> +    "prepare": "yarn build",
Is this supposed to be using `yarn`?

2020-09-10 22:54 UTC, alantrrs approved these changes
This seems to work with tchami. What's the Gruntfile doing? - Could `npm dedupe` do the same job?

2020-09-11 14:27 UTC, gitstart-firstresonance commented
> - This seems to work with tchami. What's the Gruntfile doing? - Could npm dedupe do the same job?

For some reason npm dedupe dint flatten the dependencies. The Gruntfile is basically removing any dependency that is declared as a peer dependency in the package.json

2020-09-11 17:48 UTC, alantrrs commented
Ok. Closing this PR in favor of `fr-fork` branch which has the same content.

2020-09-11 17:48 UTC, closed without merging