[ION-905] - Allow pressing enter on Image in list to continue list
FirstResonance/slate-plugins pull request #7
Opened 2020-09-15 13:24 UTC by gitstart-firstresonance

## Issue

## What I did

## Checklist

- [x] The new code matches the existing patterns and styles.
- [x] The stories still work (run `yarn storybook`).
- [x] The stories are updated when relevant: `stories` for plugins, `knobs` for options.

2020-09-15 17:14 UTC, alantrrs requested changes
- [ ] Can you write a quick paragraph on what the bug was and how this fixes it? Is this generic enough that we can push back to the original repo?
- [x] Please add a test case.
- [x] Please make sure the setup changes from fr-fork are not on this PR so we can cleanly merge into the original repo.

2020-09-16 14:57 UTC, gitstart-firstresonance commented
The issue was that the previous list implementation expects just one child per list which is a paragraph node. And whenever this is not valid, it has an unexpected behavior.

2020-09-18 06:28 UTC, alantrrs approved these changes

2020-09-18 06:29 UTC, alantrrs commented
Submitted here: https://github.com/udecode/slate-plugins/pull/276 . Closing this PR.

2020-09-18 06:29 UTC, closed without merging